# Change these first
owner: VhoraZishan # Your GitHub organization or username, where this repository lives
repo: BunkStopStatus # The name of this repository

sites:
  - name: BunkStop 
    url: https://bunkstop.vercel.app/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: BunkStopStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BunkStop Status
  introTitle: "**BunkStop** is a **free** attendance tracker for your college needs!."
  introMessage: "Here you can check the status of the BunkStop website if you are facing any issues on it."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
